#!/usr/bin/env python3
"""Weekly Intelligence Brief — Kyoto + Hermes Collaboration"""
import sys, os
# Add project folder to path so imports work
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from api_tools import get_weather, get_crypto_price, get_news
from memory import save_task
from datetime import datetime

def main():
    # 1. Fetch data using Kyoto modules
    print("🌤️ Fetching weather...")
    weather = get_weather("Tunis")
    
    print("💰 Fetching crypto prices...")
    btc = get_crypto_price("bitcoin")
    eth = get_crypto_price("ethereum")
    
    print("📰 Fetching AI news...")
    news = get_news("artificial intelligence", max_results=3)
    
    # 2. Format as Markdown
    date = datetime.now().strftime("%Y-%m-%d")
    report = f"""# 🧠 Weekly Intelligence Brief — {date}

## 🌤️ Weather (Tunis)
- Temperature: {weather['data']['temperature']}°C
- Wind: {weather['data']['wind_speed']} km/h
- Time: {weather['data']['time']}

## 💰 Crypto Prices
- Bitcoin: ${btc['data']['price_usd']:,} USD
- Ethereum: ${eth['data']['price_usd']:,} USD

## 📰 Top AI News
"""
    for i, item in enumerate(news['data'], 1):
        title = item['title'][:80] + "..." if len(item['title']) > 80 else item['title']
        report += f"{i}. [{title}]({item['url']})\n"

    report += f"\n---\n*Generated by Kyoto v2.0 • {datetime.now().strftime('%H:%M')}*\n"
    
    # 3. Save to Desktop (Using native Python open)
    filename = f"weekly_brief_{date}.md"
    path = os.path.expanduser(f"~/Desktop/01_Hermes_Output/reports/{filename}")
    with open(path, 'w', encoding='utf-8') as f:
        f.write(report)
    print(f"✅ Saved: {path}")
    
    # 4. Log to Kyoto memory (Best effort)
    try:
        save_task("weekly_brief", "success", "hermes_collab")
    except Exception as e:
        print(f"⚠️ Memory log skipped: {e}")
    
    # 5. Print summary
    print(f"\n📊 Brief complete: {weather['data']['temperature']}°C | BTC ${btc['data']['price_usd']:,} | 3 news items")
    return path

if __name__ == "__main__":
    main()
